### ISSUE TITLE
https://haskell-lang.org/news down 

### ISSUE THREAD

**Issue by kodaj** [haskell-lang/haskell-lang#129]
Hello,

Has https://haskell-lang.org/news been decommissioned? It's been giving a "no connection to server" error for several days.

Best regards,
Bence Kodaj

**Comment by bitemyapp** [comment]
Seems up for me. Closing for now, but if the problem recurs, please pipe up.

**Comment by chrisdone** [comment]
I put in a cronjob to check it on haskellnews.
