### ISSUE TITLE
News page gives Internal Server Error

### ISSUE THREAD

**Issue by kodaj** [haskell-lang/haskell-lang#134]
Hello,

I have been getting this error from https://haskell-lang.org/news since yesterday (I've tried on two different computers in two different locations): 

```
StatusCodeException (Status {statusCode = 502, statusMessage = "Bad Gateway"}) [("Server","nginx/1.10.3 (Ubuntu)"),("Date","Mon, 23 Oct 2017 09:36:54 GMT"),("Content-Type","text/html"),("Content-Length","182"),("Connection","close"),("X-Response-Body-Start","<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n"),("X-Request-URL","GET http://haskellnews.org:80/grouped?embeddable")] (CJ {expose = []})
```
Regards,
Bence Kodaj

![haskell news](https://user-images.githubusercontent.com/4332563/31882395-96d5c076-b7de-11e7-93d6-9d1a41b8e4d8.png)

**Comment by chrisdone** [comment]
Fixed! Sorry, there was a payment mishap on the Digital Ocean droplet and the server rebooted.
