### ISSUE TITLE
stack new helloworld on windows fails with obscure error

### ISSUE THREAD

**Issue by rjperrella** [haskell-lang/haskell-lang#152]
I'm completely new to Haskell. Running on Windows 10. Same output on Powershell as on CMD.exe.

Here's what I get:

C:> stack new helloworld
Downloading template "new-template" to create project "helloworld" in helloworld\ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- helloworld\helloworld.cabal

Selecting the best among 15 snapshots...

Downloaded lts-13.6 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

**Comment by snoyberg** [comment]
You need to upgrade to a newer version of Stack. Please try running stack
upgrade.

**Comment by rjperrella** [comment]
That fixed it! Thanks!
