### ISSUE TITLE
Clarify easy content contribution 

### ISSUE THREAD

**Issue by chrisdone** [haskell-lang/haskell-lang#22]
Have clear content areas of the repo and make it really easy to contribute
- Everything is Markdown
- Package tutorials
- Fork this page

We can tie all this up by updating the README to cover key contribution areas, and having a standard place (probably `static/markdown/`) where all content contribs go.

**Comment by snoyberg** [comment]
Additionally: we now have some .yaml files in config/ (though perhaps we should use a different directory instead?)
