### ISSUE TITLE
Make a VISION.md document

### ISSUE THREAD

**Issue by chrisdone** [haskell-lang/haskell-lang#23]
In which we can pop down the core goals of the site. Something like:
- Target both newbies and experts alike.
- We will target newbies by helping them find:
  - Tools that they need
  - Learning materials that they need
  - Providing helpful overviews of common most packages
- We will target experts by catering to expert use-cases, like package/API documentation
- We'll ensure that both crowds are interested in the "well-being" of the web site in terms of being up to date and useful, by making it useful for both crowds, as written above.

**Comment by snoyberg** [comment]
VISION.md exists now, can we close this?

**Comment by chrisdone** [comment]
Meant to, yeah.
