### ISSUE TITLE
Make /packages page

### ISSUE THREAD

**Issue by chrisdone** [haskell-lang/haskell-lang#27]
We make a `/packages` page (and in the nav) which shows:
- List of recommended packages (bytestring, text, vector, etc). Criterion:
  - Almost universally accepted as the right way to do it
  - Addresses common use cases
- Other common tasks with multiple options
  - E.g., tasty vs hpsec, conduit vs pipes
- Give some useful information on each, why you’d choose one or the other
- View all packages (link to https://www.stackage.org/lts)
- When relevant: include links to tutorials on the packages (self host on haskell-lang.org via the Jump project content?)

We also bring `stackage.org/lts` under `/packages/lts`, and style it as haskell-lang. Coupled with the restyled Haddocks, this brings everything (packages, haddocks, hoogle) under one user experience.

For the recommended packages, we have:
- Tutorial page per package (e.g., /tutorial/http-client) https://github.com/commercialhaskell/jump/blob/master/doc/http-client.md
- Include link to API docs
- Recommendations for writing docs: lots of examples, examples include Stack script interpreter lines

**Comment by bitemyapp** [comment]
Prior art: http://haskelliseasy.com

I was hesitant to recommend this for haskell-lang as it might miff some people, but if we're going to make getting new people the info they need our main goal we might as well go all the way.

**Comment by chrisdone** [comment]
That's pretty much what I and Michael  had in mind. I don't expect any
miffage, your list is a good list to base on, and we'd add the proposed
code samples for each. Self-contained runnable examples via stack. This
also merges in some of the work from Jump and some older initiatives we had
going, all in the same "haskell-lang" UX.

**Comment by snoyberg** [comment]
I’ve pushed an initial implementation of the packages page. I did it with a YAML config file, hoping to make it easier for people to contribute to it and for us to generate metadata and/or restructure the page in the future. It's currently up at https://ci.haskell-lang.org/packages. Feedback definitely encouraged, I think the look-and-feel could be significantly improved still.

**Comment by chrisdone** [comment]
Nice work! I'll iterate on this.

**Comment by tfausak** [comment]
There's a lot of overlap between this issue and #12. 

FWIW, I feel good unreservedly recommended Tasty over Hspec. You can easily run Hspec within Tasty via tasty-hspec, and Tasty provides a bunch of other nice stuff.

**Comment by ThibaudDauce** [comment]
I think the choice of "»" character between packages in Quick Links. It looks like an arrow and some sort of order in the package list.

Otherwise, great job! :-)

**Comment by chrisdone** [comment]
Re-assigning to myself.

**Comment by chrisdone** [comment]
My work is done on here: https://ci.haskell-lang.org/packages

What I did:
- Populated the Core packages section with all the main "core" accepted packages I could think of, from various sources. The text descriptions are brief, but that's intentional. Re-wording within the briefness limit is welcome.
- Populated the Common section with three types of packages (testing, streaming and web requesting). 

Now I'm un-assigning myself. 

Next steps are writing a tutorial for each of the “Core” packages. Most of those can be cribbed. It's a hefty bit of work, so I'll be opening a separate initiative about that. Meanwhile I'll keep this ticket open for iterating on the page me and Michael've put in place.
