### ISSUE TITLE
IRC and Mailing list page gives Internal server error

### ISSUE THREAD

**Issue by psibi** [haskell-lang/haskell-lang#30]
IRC: https://ci.haskell-lang.org/irc
Mailing list: https://ci.haskell-lang.org/mailing-lists

Error:

`hGetContents: invalid argument (invalid byte sequence)`

It does work locally.

**Comment by chrisdone** [comment]
Perhaps the deployment encoding isn't right.

**Comment by snoyberg** [comment]
Most likely that's the case. I'd recommend getting rid of any usage of `Data.Text.IO`-based file I/O and instead using bytestring I/O with explicit UTF-8 decoding calls. I can try to write a patch for that, it's probably only one or two places.

**Comment by snoyberg** [comment]
Pushed, let's see if that fixes things after deployment. @borsboom it's probably a good idea though to set the `LANG` header anyway.

**Comment by chrisdone** [comment]
Agreed!

**Comment by snoyberg** [comment]
That seemed to fix it. Good catch @psibi. Hopefully some automated link checking will catch these things in the future.
