### ISSUE TITLE
Normalize domain names

### ISSUE THREAD

**Issue by snoyberg** [haskell-lang/haskell-lang#31]
Currently, both www.haskell-lang.org and haskell-lang.org are valid for accessing the site. Ideally, one of those would simply redirect to the other. I don't have much preference one way or the other being the primary domain name. @chrisdone @borsboom thoughts?

**Comment by chrisdone** [comment]
I'd just have it redirect to haskell-lang.org, like github.com.

**Comment by borsboom** [comment]
I've updated the nginx configuration to do the redirect.
