### ISSUE TITLE
Improve "Features" blurbs?

### ISSUE THREAD

**Issue by sid-kap** [haskell-lang/haskell-lang#37]
I read through the "Features" part of the homepage that we inherited from haskell.org, and I'm not a fan of the writing style or the content. Would you guys agree?

If we want to improve this section, there are a few questions to discuss:
- Do we want to keep the "Features" section of the homepage?
- If so, do we want to keep the same 6 features, or change them?
- Once we choose which features we want to display, can we improve the blurbs?

---

Here are some of my opinions about the Features section:
- I dislike the writing style. I could give sentence-by-sentence critiques, but I think now is too early for that. We should discuss the first two questions above before discussing the third.
- The laundry list of packages is overwhelming and doesn't seem to have a particular purpose. The purpose of this section should be to demonstrate the breadth of libraries available in Haskell, so that programmers know that Haskell is a "real" language with solid ecosystem and libraries. I suggest the following:
  - To make the list less overwhelming, group the libraries by category. Maybe use some of the following categories: Networking, Web development, Systems, Streaming, Graphics, Parsing, Testing. 
  - Remove bytestring, vector, text, etc. from the list. In my opinion, showing off that your language has a string library and a vector library doesn't impress new users.
  - Bias towards libraries that are surprising. Most languages have libraries like process, directory, time, etc. Let's show people libraries that make them think, "Wow, I had no idea you could do that in Haskell!" Maybe some of the following: graphics, numerical computing/parallel computation, concurrency, networking, web frameworks, GHCJS, etc.
  - Maybe emphasize the libraries that are unique to Haskell/hard to do in other languages. The ones that come to my mind are parsing, streaming, STM, QuickCheck, DSLs for HTML/CSS/etc. 
- Maybe, instead of advertising features, we should advertise benefits: Avoid runtime/type errors! Generate high-performance, concurrent code! Reason about your code more easily! Refactor code easily!

**Comment by sid-kap** [comment]
I'm going to copy @oldmanmike's comments from #2 here, for reference:

> Then we get to the feature list. Many of the feature details aren't worded very well (in my opinion), use weird examples that don't clearly convey much, and often leave out really important properties of said features. For instance, the "Statically typed" feature details make no mention of refactorability or maintainability. As a Haskeller, I can now read between the lines and infer such a property from what's currently there, but not everyone's on-board with static type systems and the description on the home page doesn't really make the case for them. It doesn't mention algebraic data types or explicit type signatures, for instance. It just talks about how various mis-matching types will yield an error, which is probably the one thing one doesn't need to explain to new users about Haskell's static type system. Everyone knows that type errors are a thing with static type systems, that's what we historically don't like about them. "Why is Haskell's static type system different in a good way to what I've already used in Java et. al.?" In a way, I think it could be argued that we shouldn't try to make the case for Haskell's key language features right there on the home page. Instead, we should just provide a simple enumeration of features like Rust's site does and then we can link the visitor to a more in-depth summary of why each of these features matter. This would be especially helpful for Haskell's two most exotic and controversial features: pure FP and lazy evaluation. These features deserve way more justification than they're given on the site. Note the approach the Haskell Wiki took: it had the "What is Haskell?" link that presented visitors with a in-depth article that basically summarized "Why Use Haskell?" and did a relatively good job of it.

**Comment by snoyberg** [comment]
Want to send a PR to update the feature blurbs, and we can discuss there?

**Comment by sid-kap** [comment]
I created a PR (#41) on this issue a while ago. Has anyone had a chance to look at it?

**Comment by chrisdone** [comment]
Short of a totally sweet PR I don't see this issue advancing, closing.
