### ISSUE TITLE
Wrong (non-Haskell) code and table layout

### ISSUE THREAD

**Issue by jonkri** [haskell-lang/haskell-lang#46]
Looking at https://ci.haskell-lang.org/package/aeson, I'm noticing that the GHCi and table mark-up didn't get converted to HTML properly. The table markdown just gets put into a <code>p</code> element, while the non-Haskell code is just inserted as it is.

**Comment by chrisdone** [comment]
I fixed the issue with non-haskell code.

The problem with the table is that the `markdown` package does not support table syntax. I converted it to a (lamentable) HTML table.

**Comment by jonkri** [comment]
Brilliant! It looks great - thanks!
