### ISSUE TITLE
404 Not Found after following the QuickCheck link from haskell-lang.org/packages

### ISSUE THREAD

**Issue by egor-tensin** [haskell-lang/haskell-lang#47]
**Steps to reproduce:**
- go to https://haskell-lang.org/packages,
- click on the link for `quickcheck`.

**Expected result:** The `quickcheck` Stackage page should be loaded (I used the search on the main page of Stackage and found this: https://www.stackage.org/package/QuickCheck).

**Actual result:** https://www.stackage.org/package/quickcheck is loaded, saying that something was "Not Found", with the according HTTP response status code.

**Comment by psibi** [comment]
Can you send a PR fixing the link ?

**Comment by egor-tensin** [comment]
Sure, but that's already been fixed. Sorry for the delay, was trying to get this to build on Windows. Man did I suffer.

**Comment by snoyberg** [comment]
This still appears to be an issue.

**Comment by egor-tensin** [comment]
Is it? Commit e85eee1ae1b303978b4eb70e16f1dcf10e23159f fixes the issue for me. And everything seems to be fine at https://ci.haskell-lang.org/packages.

**Comment by snoyberg** [comment]
Ah, OK, we just need to deploy to prod then.
