### ISSUE TITLE
Add intero to "get started"

### ISSUE THREAD

**Issue by ketzacoatl** [haskell-lang/haskell-lang#48]
Intero has recently been added to the site - https://haskell-lang.org/intero (yay!)

Looking over https://haskell-lang.org/get-started, I believe adding intero to that page would make a lot of sense.. definitely in the "next steps" section, possibly also including a mention in the list of reasons why stack is great (you get to use intero!).

**Comment by chrisdone** [comment]
Agreed - just have to put it in the page.

**Comment by ketzacoatl** [comment]
There's my first attempt! Feel free to recommend better wording if you have any..
