### ISSUE TITLE
Add a purpose statement on r/haskell_lang

### ISSUE THREAD

**Issue by sjakobi** [haskell-lang/haskell-lang#49]
In the recent discussion threads on Hacker News and r/haskell about haskell-lang.org there has been some confusion on the purpose of the new r/haskell_lang subreddit.

It would be good to add a short paragraph on r/haskell_lang that explains the purpose of the subreddit. For example:

> This subreddit is intended for discussions and questions regarding the haskell-lang.org website.

**Comment by snoyberg** [comment]
I've added a first stab of a sidebar to the subreddit, though I'm hoping others will give some feedback here (and maybe on the subreddit itself) and give some updates.

**Comment by kluge** [comment]
The title of /r/haskell_lang is "Discussion of the Haskell programming language", which doesn't match the current sidebar description.

**Comment by snoyberg** [comment]
Good catch, updated.

**Comment by snoyberg** [comment]
It looks like there are no recommendations for improvements to that text, closing.
