### ISSUE TITLE
Remove `stack hoogle` feature from Get Started page until it has been properly released

### ISSUE THREAD

**Issue by sjakobi** [haskell-lang/haskell-lang#50]
I think the current state of the page gives the impression that `stack hoogle` has already been released.

**Comment by chrisdone** [comment]
In that case it's not talking about `stack hoogle`. It's just that hoogle is installable. I guess we could remove it for now.

**Comment by sjakobi** [comment]
> In that case it's not talking about stack hoogle.

Ok. I guess I got confused by the introducing "With the Haskell Stack you get …".

It's not clear to me whether "the Haskell Stack" means `stack` or not.
