### ISSUE TITLE
Clarify purpose of /r/haskell-lang

### ISSUE THREAD

**Issue by simonyangme** [haskell-lang/haskell-lang#53]
In relation to: https://www.reddit.com/r/haskell_lang/comments/4rv4uu/is_this_the_official_haskell_subreddit_or_is/d54cpja

This should be reflected both in the sidebar of subreddit as well as in the announcement post.

**Comment by snoyberg** [comment]
Dupe of #49, closing this issue so we don't end up with discussion in two different threads. Thanks for opening this.
