### ISSUE TITLE
Q: License for content on http://haskell-lang.org?

### ISSUE THREAD

**Issue by hvr** [haskell-lang/haskell-lang#70]
I see that the top-level LICENSE file places this Git repo under BSD3 terms. Does this also apply to the documentation/tutorials that are currently worked upon? I'm asking because those are looking quite useful and I'm considering integrating parts into teaching material of mine. In order to do that, some level of legal certainty would be desirable. Hence this question. Do you plan to stay with BSD3 terms for the content?

**Comment by chrisdone** [comment]
The whole codebase including markdown files are intended to be BSD3-licensed. 👍
