### ISSUE TITLE
Tutorial/library page improvements and dedupe

### ISSUE THREAD

**Issue by snoyberg** [haskell-lang/haskell-lang#79]
- [x] Unify the codebase between the tutorials and the library pages
- [x] Add a "Discuss on Reddit" link next to the Github link
- [x] Add a "Share on Twitter" link next to the Reddit link

**Comment by snoyberg** [comment]
Done!

**Comment by oerjan** [comment]
I just found a link to this in a Reddit thread from July, and I want to mention that Reddit threads get locked after 6 (IIRC) months.

**Comment by snoyberg** [comment]
Which Reddit thread?

**Comment by oerjan** [comment]
https://www.reddit.com/r/haskell/comments/4uzok7/exception_safety_in_haskell/d5vlqtt

Silly me, there was a comment replying to you already pointing out this.
