### ISSUE TITLE
Add some tutorials from Jump docs

### ISSUE THREAD

**Issue by psibi** [haskell-lang/haskell-lang#80]
Since incorporating remote tutorial has been implemented, why not bring some nice tutorial from Jump: https://github.com/commercialhaskell/jump/tree/master/doc

I would specifically like the `http-client` and the `command line parsing` tutorial.

**Comment by snoyberg** [comment]
Agreed in principle, please go ahead with including them! For the two examples provided, however, I think we've already copied the content over into https://github.com/haskell-lang/haskell-lang/blob/master/static/tutorial/package-http-client.md and https://github.com/haskell-lang/haskell-lang/blob/master/static/tutorial/package-optparse-applicative.md (we should probably remove the `jump` copy or transclude from there instead).

**Comment by borsboom** [comment]
The package-optparse-applicative docs are similarly structured, but the code is completely different because because it doesn't use optparse-simple.

**Comment by snoyberg** [comment]
I discussed with other Jump contributors. Between haskell-lang being a great place for hosting docs, and Foundation being the new innovative standard library people are playing with, Jump doesn't have much to offer on its own. Let's merge all the relevant docs into haskell-lang, and then shut down Jump.

**Comment by snoyberg** [comment]
Merged in.
