### ISSUE TITLE
Intero recommendation on downloads page seems out of place

### ISSUE THREAD

**Issue by ndmitchell** [haskell-lang/haskell-lang#85]
The downloads page is light and crisp. It advertises haddock/stack/ghc - all things which no modern Haskeller can be without, and all of which are stable and production ready beyond a shadow of a doubt. It also advertises Intero, which as far as I can tell, is Emacs only, much newer, and still under heavy development. I worry the Intero advert confuses the issues, and sends people down a route where many will ultimately not be happy (e.g. "urgh, i have to use Emacs for Haskell development") - while also brushing over lots of widely used alternatives (e.g. Leskah, haskell-mode, SublimeHaskell).

I'm not doubting the quality of Intero, it certainly seems pretty awesome, I just don't think it fits well with the rest of the set.

**Comment by bitemyapp** [comment]
I concur, with the proviso that when intero is more stable and has frontends for more editors, it'd be something users would look for albeit perhaps not on a downloads page. I think the keyword here is "IDE".

**Comment by chrisdone** [comment]
Agreed, let's remove it from that page and find a better place to put it.

**Comment by ndmitchell** [comment]
I think having an IDE page would be a great addition. Since an IDE is definitely not one size fits all (everyone has very entrenched preferences) having a small embedded GIFs for each option would let people pick what suits them.

**Comment by chrisdone** [comment]
@ndmitchell @bitemyapp Yeah, an IDE page would be ideal. I'm not too comfortable recommending anything to a general audience, but I guess we have to start somewhere in leading people to that. At least stack + an editor is a pretty reliable experience. Our clients commented that using Atom/Sublime/Vim/Whatever isn't a big deal but that Stack was a big improvement.

**Comment by ndmitchell** [comment]
Stack makes a huge difference, but I still find that using an IDE gives another bump in productivity, even if it's something as simple as Ghcid. It's certainly worth linking to an IDE page.

**Comment by chrisdone** [comment]
Oh, definitely. Do you want to make a Gist .md file with a proposal for such a page's content?

**Comment by ndmitchell** [comment]
https://gist.github.com/ndmitchell/298d0a9e71b4105522e07b544df67b5b was the direction I was thinking of. I'm not sure which other IDE's are considered "production worthy" by their authors (the list seems to change regularly). Certainly I know people who have got Atom, Sublime and Vim working with various tools - but not sure which.

I would suggest the Intero page say whether it supports SpaceMacs or not - that seems a fairly standard Emacs variant that a lot of people are switching to.

**Comment by chrisdone** [comment]
Makes sense. Can we get users of other IDEs or editors to chime in perhaps? @nh2 uses SublimeHaskell; would you be interested in putting something on an IDEs page on haskell-lang.org?

**Comment by nh2** [comment]
I like the idea of showing a quick GIF of how it works as you have in the proposal. In SublimeHaskell we have a couple of those on the README page that could be used: https://github.com/SublimeHaskell/SublimeHaskell/

**Comment by nh2** [comment]
CC @mvoidex
