### ISSUE TITLE
Better "next steps" tutorials for "Get started" page

### ISSUE THREAD

**Issue by snoyberg** [haskell-lang/haskell-lang#89]
I was discussing with @bitemyapp, and it seems like we have some room to improve the "Next steps" in the get started page with targeted usage tutorials. We identified three different common use cases we could see addressed:
- "How to play": tutorial on using Stack+GHCi to experiment with code
- "How to script": tutorial on using `stack runghc` to write short programs
- "How to build a project": tutorial on Stack's more powerful feature set around `stack new`, `stack build`, etc

It might make sense to have these three as their own Stack tutorial section (with a link "learn more at haskellstack.org"), and then a fourth section for "what's next."

**Comment by vincenthz** [comment]
I think a fourth section "How to integrate with $IDE" would be extremely useful; In my case with atom, it took a bit of efforts of identifying what to do (specially since I accumulated too many old state)

**Comment by snoyberg** [comment]
Definitely desired content, issue tracking it is #21.

**Comment by vincenthz** [comment]
some more advanced topics like "how to profile" and "hpc" your stack project, would be awesome too.

**Comment by chrisdone** [comment]
👍 I like this separation of play, script and build. It gives much more concrete next steps and addresses the major use-cases nicely.

**Comment by soupi** [comment]
Can [this](https://github.com/soupi/rfc/blob/master/getting-started-haskell-stack.md) be used for the "How to play" part?

**Comment by snoyberg** [comment]
PR #94 is open for this. I can take a crack at the how to build later, or anyone else is welcome to hit it first. Also, feel free to hack to death what I wrote.

**Comment by snoyberg** [comment]
This is now implemented and merge to prod, closing.
