### ISSUE TITLE
Improve locally hosted tutorials titles

### ISSUE THREAD

**Issue by ThibaudDauce** [haskell-lang/haskell-lang#90]
Hi,

In the [documentation page](https://haskell-lang.org/documentation), I think title for the packages' tutorials could be improved.

For example : "How to parse and encode JSON" instead of "aeson library" or "How to send HTTP requests" instead of "http-client library". What do you think? It will be much easier for a new haskeller to visually parse the links and find what it needs.

**Comment by bitemyapp** [comment]
I concur.

Example: http://haskelliseasy.com

**Comment by snoyberg** [comment]
I've opened PR #97. Anyone want to check it out before I merge to master?
