### ISSUE TITLE
Operator Glossary is missing <|>

### ISSUE THREAD

**Issue by wfranzini** [haskell-lang/haskell-lang#92]
Hi,

if I'm not wrong the "Operator Glossary" page is missing <|> defined in Control.Applicative for the Alternative class.

HTH
walter

**Comment by snoyberg** [comment]
That's a good catch. Would you be interested in giving a stab at some content for it?

**Comment by wfranzini** [comment]
I'm not up to the job, Haskell is still a foreign language for me :-)

**Comment by snoyberg** [comment]
Fair enough, just wanted to give you the option if you were interested.
Thanks again for the report.
